[[imports]]
  path = "github.com/frjo/hugo-theme-zen"

# See: https://gohugo.io/hugo-modules/configuration/#module-config-mounts
#   if you add a mounts section you should remove the old staticDir etc. settings.
#   When you add a mount, the default mount for the concerned target root is ignored: be sure to explicitly add it.
  [[mounts]]
    source = "archetypes"
    target = "archetypes"

  [[mounts]]
    source = "assets"
    target = "assets"

  #[[mounts]]
  #  source = "content/eng-ph"
  #  target = "content"
  #  lang = "en"                                        # when in multihost / multilang mode
  [[mounts]]
    source = "content/en-ph"
    target = "content"
    lang = "en-ph"                                      # when in multihost / multilang mode
  [[mounts]]
    source = "content/ja"
    target = "content"
    lang = "ja"                                         # when in multihost / multilang mode
  [[mounts]]
    source = "content/ko"
    target = "content"
    lang = "ko"                                         # when in multihost / multilang mode

  [[mounts]]
    source = "data"
    target = "data"

  [[mounts]]
    source = "i18n"
    target = "i18n"

  [[mounts]]
    source = "layouts"
    target = "layouts"

  #[[mounts]]
  #  source = "static/eng-ph"
  #  target = "static"
  #  lang = "en"                                        # when in multihost / multilang mode
  [[mounts]]
    source = "static/en"
    target = "static"
    lang = "en-ph"                                      # when in multihost / multilang mode
  [[mounts]]
    source = "static/ja"
    target = "static"
    lang = "ja"                                         # when in multihost / multilang mode
  [[mounts]]
    source = "static/ko"
    target = "static"
    lang = "ko"                                         # when in multihost / multilang mode
