#mainSections = ["blog", "posts"]                                             # Hugo default
#mainTypes = ["article", "sitepage", "review"]                                                # YourOnly.One

### BGN: Structured Data ###
  description = "YourOnly.One's Hugo Test Site"
### END: Structured Data ###

### BGN: Theme settings
  copyright = "This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/)."
  footer = "[YourOnly.One](https://im.youronly.one/)"
  mobileMenu = true
  sidebar = false
  submitted = true
  poweredby = true
  logoWidth = 64
  imageMaxWidth = 400
  feedlinks = true
  contact  = ""
  #dateformat =
  #favicon = ""
  #icon = ""
  #image = ""
  #realfavicongenerator = ""

  [[socials]]
  name = "YourOnly.One"
  link = "https://im.youronly.one/"
### END: Theme settings

### BGN: Other Settings ###
### END: Other Settings ###
